\documentclass[article,nojss]{jss}


<<package,include=FALSE,echo=FALSE>>=
options(keep.source = TRUE, width = 60)
packageInfo <- packageDescription("DNAPlotR")
library(DNAPlotR)
packageKeywords<-"visualization, alignment, display, genome, DNA, sequence, multiple sequence alignment, reference sequence"
@
%\VignetteIndexEntry{\Sexpr{packageInfo$Package} examples}
%\VignetteDepends{}
%\VignetteKeywords{\Sexpr{packageKeywords}}
%\VignettePackage{\Sexpr{packageInfo$Package}}

\title{\pkg{\Sexpr{packageInfo$Package}} package example (version \Sexpr{packageInfo$Version})}
\author{\Sexpr{packageInfo$Author}}
\Plainauthor{\Sexpr{packageInfo$Author}}

\Address{
  Github: \url{http://github.com/sherrillmix/dnaplotr}
}

\Keywords{\Sexpr{packageKeywords}}

\Abstract{
  This is a collection of examples of usage for the \pkg{\Sexpr{packageInfo$Package}} package.
}

\begin{document}
\SweaveOpts{engine=R,eps=FALSE}

\section{General description}

This is an example of using the \pkg{DNAPlotR} package in R.
<<plotDNA, echo=TRUE, eval=FALSE>>=
  set.seed(1234)
  fakeSeqs<-createFakeDNA(5000,500)
  refSeq<-fakeSeqs[1]
  fakeSeqs<-fakeSeqs[-1]
  species<-sprintf('Species %s',sub(' [0-9]+$','',names(fakeSeqs)))
  par(mar=c(3.5,4.4,.5,7),mgp=c(2.5,1,0))
  dummy<-plotDNA(fakeSeqs,groups=species)
@

\begin{figure}[htbp]
\begin{center}
<<showPlotDNA, fig=TRUE, height=4.5, width=8, echo=FALSE>>=
<<plotDNA>>
@
\label{figPlotDNA}
\caption{An example of a DNA plot}
\end{center}
\end{figure}




\end{document}
