context("Plot DNA")
test_that("Check if indexToRange works",{
	expect_that(indexToRange(c(1:5,10:7)), equals(data.frame('start'=c(1,7),'end'=c(5,10))))
	expect_that(indexToRange(c(1:5,6:10,9999:11)), equals(data.frame('start'=c(1),'end'=c(9999))))
	expect_that(indexToRange(c(1:5,6:10,9999:11,1:5,1:5)), equals(data.frame('start'=c(1),'end'=c(9999))))
	expect_that(nrow(indexToRange(seq(1,999,2))), equals(500))
})

test_that("Check if gapToNoGap works",{
	expect_that(gapToNoGap('AAAAAAAAAAA',1:5), equals(1:5))
	expect_that(is.na(gapToNoGap('AAAAAAAAAAA',99)), is_true())
	expect_that(is.na(gapToNoGap('AA',3)), is_true())
	expect_that(is.na(gapToNoGap('AA',-1)), is_true())
	expect_that(is.na(gapToNoGap('AA',0)), is_true())
	expect_that(is.na(gapToNoGap('AA',c(0,-1,100))), equals(c(TRUE,TRUE,TRUE)))
	expect_that(gapToNoGap('AA',2), equals(2))
	expect_that(gapToNoGap('A-A',2), equals(1))
	expect_that(gapToNoGap('A----A',5), equals(1))
	expect_that(gapToNoGap('A----A',6), equals(2))
	expect_that(gapToNoGap('A----A',1:6), equals(c(1,1,1,1,1,2)))
	expect_that(gapToNoGap('Z--Z--Z',1:7), equals(c(1,1,1,2,2,2,3)))
	expect_that(gapToNoGap('--A--A--A',1:9), equals(c(0,0,1,1,1,2,2,2,3)))
	expect_that(is.na(gapToNoGap('--A--A--A',c(NA,NA,1))), equals(c(TRUE,TRUE,FALSE)))
})

test_that("Check if noGapToGap works",{
	expect_that(noGapToGap('AAAAAAAAAAA',1:5), equals(1:5))
	expect_that(is.na(noGapToGap('AAAAAAAAAAA',99)), is_true())
	expect_that(is.na(noGapToGap('AA',3)), is_true())
	expect_that(is.na(noGapToGap('AA',-1)), is_true())
	expect_that(is.na(noGapToGap('AA',0)), is_true())
	expect_that(is.na(noGapToGap('AA',c(0,-100,100))), equals(c(TRUE,TRUE,TRUE)))
	expect_that(noGapToGap('AA',2), equals(2))
	expect_that(noGapToGap('A-A',2), equals(3))
	expect_that(noGapToGap('A----A',2), equals(6))
	expect_that(noGapToGap('A----A-A--A',3), equals(8))
	expect_that(noGapToGap('A--A--A-AA--A',1:6), equals(c(1,4,7,9,10,13)))
	expect_that(noGapToGap('--Z--Z--Z---',1:3), equals(c(3,6,9)))
	expect_that(is.na(noGapToGap('--A--A--A',c(NA,NA,1))), equals(c(TRUE,TRUE,FALSE)))
})

test_that("Check if seqSplit works",{
	expect_that(dim(seqSplit('AAA','AAZ')), equals(c(2,3)))
	expect_that(dim(seqSplit('AAA','AAZ','AAT')), equals(c(3,3)))
	expect_that(dim(seqSplit('AAA','AAZ','A')), throws_error('not same length'))
	expect_that(dim(seqSplit('AAA','AAZ','A',fill='-')), equals(c(3,3)))
	expect_that(dim(seqSplit(c('AAA','AAZ'),'A',fill='-')), equals(c(3,3)))
	expect_that(dim(seqSplit(c('AAA','AAZ'),c('A','TT'),fill='-')), equals(c(4,3)))
	expect_that(seqSplit(c('AAA','AAZ'),NA,fill='-'), throws_error('NA sequence found'))
	expect_that(seqSplit(c('AAA','AAZ',''),fill='*')[3,], equals(c('*','*','*')))
	expect_that(seqSplit('AA','AAZA','',fill='-')[3,], equals(rep('-',4)))
	expect_that(dim(seqSplit(sapply(0:1000,function(x)paste(sample(letters,x,TRUE),collapse='')),fill='~')), equals(c(1001,1000)))
  expect_that(seqSplit(c("AAA","CCC","CTC"))[,1],equals(c('A','C','C')))
  expect_that(seqSplit(c("AAA","CCC","CTC"))[1,],equals(c('A','A','A')))
  expect_that(seqSplit(c("AAA","CC","CTC"))[1,],throws_error('length'))
  expect_that(seqSplit(c("AAA",NA,"CTC"))[1,],throws_error('NA'))
  expect_that(seqSplit(c("AAA",NA,"CTC"),fill='-')[1,],throws_error('NA'))
  expect_that(seqSplit(c("AAA",'CC',"CTC"),fill='-')[,3],equals(c('A','-','C')))
  expect_that(seqSplit(c("AAA",'CC',"CTC"),fill='@')[,3],equals(c('A','@','C')))
  expect_that(dim(seqSplit(replicate(123,paste(sample(letters,543,TRUE),collapse='')))),equals(c(123,543)))
  expect_that(dim(seqSplit(c('A',replicate(123,paste(sample(letters,543,TRUE),collapse=''))),fill='!')),equals(c(124,543)))
  expect_that(dim(seqSplit(c('A',replicate(123,paste(sample(letters,543,TRUE),collapse=''))),fill='THISISSILLYBUTDOESNTBREAK')),equals(c(124,543)))
})

test_that("Check if replaceOuterGaps works",{
	expect_that(replaceOuterGaps(c('AAA','AAZZZ')), equals(c('AAA','AAZZZ')))
	expect_that(replaceOuterGaps(c('AA--A','AAZ-------ZZ')), equals(c('AA--A','AAZ-------ZZ')))
	expect_that(replaceOuterGaps(c('---AA--A','AAZ-------ZZ----','--A-')), equals(c('...AA--A','AAZ-------ZZ....','..A.')))
	expect_that(replaceOuterGaps(c('---AA--A','AAZ-------ZZ----','--A-'),leftEnd=FALSE), equals(c('---AA--A','AAZ-------ZZ....','--A.')))
	expect_that(replaceOuterGaps(c('---AA--A','AAZ-------ZZ----','--A-'),rightEnd=FALSE), equals(c('...AA--A','AAZ-------ZZ----','..A-')))
	expect_that(replaceOuterGaps(c('---AA--A','AAZ-------ZZ----','--A-'),rightEnd=FALSE,leftEnd=FALSE), equals(c('---AA--A','AAZ-------ZZ----','--A-')))
	expect_that(replaceOuterGaps(c(NA,'---AA--A','AAZ-------ZZ----','--A-')), throws_error('NA sequence found'))
})

test_that("Check if removeGapCols works",{
	expect_that(removeGapCols(c('AAAZZ','AAZZZ')), equals(c('AAAZZ','AAZZZ')))
	expect_that(removeGapCols(c('AA--A','AAZZZ')), equals(c('AA--A','AAZZZ')))
	expect_that(removeGapCols(c('A-A','C-C','C-C','TAT'),maxGapProp=.74), equals(c('AA','CC','CC','TT')))
	expect_that(removeGapCols(c('A-A','C-C','C-C','TAT'),maxGapProp=.75), equals(c('A-A','C-C','C-C','TAT')))
	expect_that(removeGapCols(c('A-A','C-C','C-C','TAT'),maxGapProp=-.01), equals(c('','','','')))
	expect_that(removeGapCols(c('A-A','C-C','C-C','TAT'),maxGapProp=-.01), equals(c('','','','')))
	expect_that(removeGapCols(c('A-A','C-C','C-C','T-T'),maxGapProp=1), equals(c('A-A','C-C','C-C','T-T')))
	expect_that(removeGapCols(c(NA,'---AA--A','AAZ-------ZZ----','--A-')), throws_error('NA sequence found'))
})

test_that("Check if replaceAfterStop works",{
	expect_that(replaceAfterStop(c('AAA','AAZZZ')), equals(c('AAA','AAZZZ')))
	expect_that(replaceAfterStop(c('AA--A','AAZ-------ZZ')), equals(c('AA--A','AAZ-------ZZ')))
	expect_that(replaceAfterStop(c('AXAAXAA','AAAAAAAA','AAAX')), equals(c('AXXXXXX','AAAAAAAA','AAAX')))
	expect_that(replaceAfterStop(c('AXAAXAA','AAAAAAAA','AAAX'),'Z'), equals(c('AXAAXAA','AAAAAAAA','AAAX')))
	expect_that(replaceAfterStop(c('AXZAZAA','AAAAXAAA','AAAZ'),'Z'), equals(c('AXZXXXX','AAAAXAAA','AAAZ')))
	expect_that(replaceAfterStop(c('AZAAZAA','AAAAAAAA','AAAZ'),'Z','!'), equals(c('AZ!!!!!','AAAAAAAA','AAAZ')))
	expect_that(replaceAfterStop(c('AAAXA','AAZXXAAAXA',NA,'ASDASADS')), throws_error('NA sequence found'))
})


test_that("Check if indexToRange works",{
	expect_that(indexToRange(1:10)$start, equals(1))
	expect_that(indexToRange(1:100)$start, equals(1))
	expect_that(indexToRange(c(1:100,123:234))$start, equals(c(1,123)))
	expect_that(indexToRange(c(1:100,10:234))$start, equals(c(1)))
	expect_that(indexToRange(c(1,3,5,6))$start, equals(c(1,3,5)))
	expect_that(indexToRange(1:10)$end, equals(10))
	expect_that(indexToRange(1:100)$end, equals(100))
	expect_that(indexToRange(c(1:100,123:234))$end, equals(c(100,234)))
	expect_that(indexToRange(c(1:100,10:234))$end, equals(c(234)))
	expect_that(indexToRange(c(1,3,5,6))$end, equals(c(1,3,6)))
})


test_that("plotDNA works",{
  expect_that(plotDNA(c("AAA","CCC","CTC")),is_null())
  expect_that(plotDNA(c("ZZXZX","CCC","CTC")),is_null())
  expect_that(plotDNA(c("AA-","CC.","CTC")),is_null())
  expect_that(plotDNA(c("AA-","CC.","CTC"),groups=c(1,1,2)),is_null())
  expect_that(plotDNA(c("AA-","CC.","CTC"),groups=c(1,1)),throws_error('[Ll]ength'))
  expect_that(plotDNA(c("AA-","CC.","CTC"),seqCounts=c(1,1,100)),is_null())
  expect_that(plotDNA(c()),throws_error('missing')) #is this desired?
  expect_that(plotDNA(NULL),throws_error('missing')) #is this desired?
  expect_that(plotDNA(c("AA-","CC.","CTC"),seqCounts=c(1,1)),throws_error('[Ll]ength'))
  expect_that(plotDNA(c("AA-","CC.","CTC"),refSeq='A-A'),is_null())
})

test_that("plotAA works",{
  expect_that(plotAA(c("AAA","CCC","CTC")),is_null())
  expect_that(plotAA(c("ZZXZX","CCC","CTC")),is_null())
  expect_that(plotAA(c("AA-","CC.","CTC")),is_null())
})

test_that("createFakeDNA works",{
  expect_that(length(createFakeDNA(500)),equals(500+1))
  expect_that(length(createFakeDNA(10)),equals(10+1))
  expect_that(length(unique(nchar(createFakeDNA(500,400)))),equals(1))
  expect_that(unique(nchar(createFakeDNA(500,500))),equals(500))
  expect_that(unique(nchar(createFakeDNA(1000,20))),equals(20))
  expect_that(unique(nchar(createFakeDNA(1000,20,nSplit=0))),equals(20))
  expect_that(any(grepl('[^ACTG-]',(createFakeDNA(1000,500)))),equals(FALSE))
  expect_that(any(grepl('[^ZYX-]',(createFakeDNA(1000,500,bases=c('Z','Y','X'))))),equals(FALSE))
  expect_that(any(grepl('[^ZYX]',(createFakeDNA(1000,500,pGap=0,bases=c('Z','Y','X'))))),equals(FALSE))
  expect_that(length(unique(createFakeDNA(1000,500,pGap=0,pMutation=0,pNoise=0,bases=c('Z','Y','X')))),equals(1))
})

test_that("createFakeAA works",{
  expect_that(length(createFakeAA(500)),equals(500+1))
  expect_that(length(createFakeAA(10)),equals(10+1))
  expect_that(length(unique(nchar(createFakeAA(500,400)))),equals(1))
  expect_that(unique(nchar(createFakeAA(500,500))),equals(500))
  expect_that(unique(nchar(createFakeAA(1000,20))),equals(20))
})
